# Generated by Django 2.0.6 on 2018-06-28 14:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('feed', '0002_post'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ExampleModel',
        ),
    ]
